"""Unified recruiter memory: load rows and render prompt blocks.

Memory has two kinds:
  - fact:        confirmed preference. Feeds the planner (soft bias) and agent.
  - observation: profiler hypothesis. Agent-only, confirmation-gated.

The usage contract lives here so every consumer injects the same rules.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import asyncpg

from pipeline.observability import (
    start_span as _obs_start_span,
    update_current_span as _obs_update_current_span,
)

# Observations below this never reach the agent prompt.
SURFACE_CONFIDENCE = 0.7
MAX_OBSERVATIONS_IN_PROMPT = 3
SURFACE_COOLDOWN_DAYS = 7

AGENT_MEMORY_RULES = """\
RULES for using this memory:
1. Facts are confirmed preferences. Treat them as default soft preferences for every search, but only explicitly mention them if they actively change your plan for the current turn.
2. Observations are unconfirmed hypotheses generated by a background profiler. NEVER apply them to a search.
3. The ONLY action allowed for an observation is to ask the recruiter to confirm it. Ask at most ONE observation question per session, and only if it is highly relevant to the current context.
4. When asking, phrase it conversationally: "I noticed you often accept candidates with React experience. Want me to prioritize React in future searches?" Do NOT call the confirm_observation tool yet; wait for their answer.
5. Once the recruiter answers, use the `confirm_observation` tool. If they say yes, pass `accept=true`. If no, pass `accept=false`.
6. Never enumerate this memory unprompted. If explicitly asked what you know about the user, list facts first, then unconfirmed observations with their confidence %."""


@dataclass
class MemoryFact:
    id: str
    content: str
    category: str = "other"
    source: str = "manual"


@dataclass
class MemoryObservation:
    id: str
    content: str
    category: str
    confidence: float
    evidence_count: int = 1


@dataclass
class MemoryBundle:
    enabled: bool = True
    facts: list[MemoryFact] = field(default_factory=list)
    observations: list[MemoryObservation] = field(default_factory=list)


async def load_memory(pool: asyncpg.Pool, recruiter_id: str) -> MemoryBundle:
    """Fetch active memory. Fail-open: any error returns an empty enabled bundle."""
    if not recruiter_id:
        return MemoryBundle()
    with _obs_start_span("agent.memory.load", input={"recruiter_id": recruiter_id}):
        try:
            enabled_row = await pool.fetchrow(
                """SELECT personalization_enabled FROM recruiter_preferences
                   WHERE recruiter_id = $1::uuid""", recruiter_id)
            enabled = bool(enabled_row["personalization_enabled"]) if enabled_row else False
            if not enabled:
                _obs_update_current_span(output={"enabled": False, "facts": 0, "observations": 0})
                return MemoryBundle(enabled=False)
            rows = await pool.fetch(
                """SELECT id, kind, category, content, confidence, evidence_count,
                          last_surfaced_at
                   FROM recruiter_memory
                   WHERE recruiter_id = $1::uuid AND status = 'active'
                   ORDER BY kind, confidence DESC, last_evidence_at DESC""",
                recruiter_id)
        except Exception:
            _obs_update_current_span(output={"error": "db_fetch_failed"})
            return MemoryBundle()
        bundle = MemoryBundle(enabled=True)
        for r in rows:
            if r["kind"] == "fact":
                bundle.facts.append(MemoryFact(
                    id=str(r["id"]), content=r["content"], category=r["category"]))
            else:
                bundle.observations.append(MemoryObservation(
                    id=str(r["id"]), content=r["content"], category=r["category"],
                    confidence=float(r["confidence"]),
                    evidence_count=int(r["evidence_count"])))
        _obs_update_current_span(output={
            "enabled": True,
            "facts": len(bundle.facts),
            "observations": len(bundle.observations),
        })
        return bundle


def build_agent_memory_block(
    facts: list[MemoryFact],
    observations: list[MemoryObservation],
) -> str:
    """Render the agent system-prompt memory section, or '' if nothing to say."""
    surfaced = [o for o in observations if o.confidence >= SURFACE_CONFIDENCE]
    surfaced = surfaced[:MAX_OBSERVATIONS_IN_PROMPT]
    if not facts and not surfaced:
        return ""
    lines: list[str] = ["## Recruiter Memory"]
    if facts:
        lines.append("\nConfirmed preferences (facts):")
        lines += [f"- {f.content}" for f in facts]
    if surfaced:
        lines.append("\nUnconfirmed observations (confirmation-gated):")
        lines += [
            f"- [{o.id}] {o.content} (confidence {o.confidence:.0%}, "
            f"seen {o.evidence_count}x)"
            for o in surfaced
        ]
    lines.append("\n" + AGENT_MEMORY_RULES)
    return "\n".join(lines)
